// Generated by Selenium IDE

using System;
using System.Collections.Generic;
using NUnit.Framework;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;

namespace Selenium;

[TestFixture]
[Obsolete]
public class AuthorizeTestOld
{
    private IWebDriver driver;
    public IDictionary<string, object> vars { get; private set; }
    private IJavaScriptExecutor js;

    [SetUp]
    public void SetUp()
    {
        driver = new ChromeDriver();
        js = (IJavaScriptExecutor) driver;
        vars = new Dictionary<string, object>();
    }

    [TearDown]
    protected void TearDown()
    {
        driver.Quit();
    }

    [Test]
    public void authorize()
    {
        driver.Navigate().GoToUrl("http://planscam.somee.com/");
        driver.Manage().Window.Size = new System.Drawing.Size(1920, 1040);
        driver.FindElement(By.LinkText("Login")).Click();
        driver.FindElement(By.Id("UserName")).Click();
        driver.FindElement(By.Id("UserName")).SendKeys("Clown");
        driver.FindElement(By.CssSelector(".editor-label:nth-child(3) > label")).Click();
        driver.FindElement(By.Id("Password")).SendKeys("t6QTkqyPcfEPvja~");
        driver.FindElement(By.CssSelector("input:nth-child(8)")).Click();
    }
}